name: common jobs

jobs:
    Check_Test:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2

            - name: Check IMAGE_TAG
              run: echo test-check-test

            